version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app 
    restart: unless-stopped  # Reinicio del servicio a menos que se detenga manualmente